// <auto-generated />
using System;
using HypeHubDAL.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HypeHubDAL.Migrations.Users
{
    [DbContext(typeof(UsersContext))]
    [Migration("20231026133710_InitialCreateWithSeeds")]
    partial class InitialCreateWithSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HypeHubDAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ae6be6d-5d79-4d85-902c-40451aec5f75",
                            Email = "Gamer123@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMER123@GMAIL.COM",
                            NormalizedUserName = "GAMER123",
                            PasswordHash = "AQAAAAIAAYagAAAAEJZFfvYfFtQ49J3uXSJxY4GmulXEmfRFZMDEuS2S/5Gq5XBCfOow2ocI/D0cRbL8Zg==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "27be5e3f-be62-4c2c-9dfc-9f1c4550a68e",
                            TwoFactorEnabled = false,
                            UserName = "Gamer123"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d316d7d-88cb-42ee-872b-4d8109bca236",
                            Email = "GameMaster@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMEMASTER@GMAIL.COM",
                            NormalizedUserName = "GAMEMASTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDwMctckCcur7RFuv4yeOFlzmgdJFNc+VTyt/RNcfWBPoGsQsTqZinMPh6s5jFxYg==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "65e6e9bb-94f0-4fea-929e-3106c49b027d",
                            TwoFactorEnabled = false,
                            UserName = "GameMaster"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc45b47f-2918-44f1-a313-612c2aa8f139",
                            Email = "ProPlayer@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PROPLAYER@GMAIL.COM",
                            NormalizedUserName = "PROPLAYER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMNRBFj59VNyLwf42uypOuBwxUUFarLt/nokY1hK1wq67nrjskqgHuMLsj496K8UxA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "981a2d6b-6f5a-433e-8e79-712b6f3ca9a5",
                            TwoFactorEnabled = false,
                            UserName = "ProPlayer"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3841c922-6578-4eef-b387-250ae5210b0d",
                            Email = "NinjaGamer@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NINJAGAMER@GMAIL.COM",
                            NormalizedUserName = "NINJAGAMER",
                            PasswordHash = "AQAAAAIAAYagAAAAEH0+aegRuWeV1z36OmPxn3kQuFDi4d6LZIikdaNgj8wgwJMIptSSBEpFHFpUHnYMag==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "49c346d1-b78b-4843-9d0a-3639f942a3b3",
                            TwoFactorEnabled = false,
                            UserName = "NinjaGamer"
                        },
                        new
                        {
                            Id = "55555555-5555-5555-5555-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f062d51e-f917-433d-b8fb-7e2bfae58a0c",
                            Email = "NoobSlayer@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NOOBSLAYER@GMAIL.COM",
                            NormalizedUserName = "NOOBSLAYER",
                            PasswordHash = "AQAAAAIAAYagAAAAENKeoITOuv4dldrma/NpYOTszIaWInboSuBllI2yXxNsdTbyfzrBHhfYpoSTdrLRSA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "59acd55a-bc21-4382-9b76-32c87736e2a1",
                            TwoFactorEnabled = false,
                            UserName = "NoobSlayer"
                        },
                        new
                        {
                            Id = "66666666-6666-6666-6666-666666666666",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "544df8af-2e8d-4364-9c83-00b2cddc01e6",
                            Email = "EpicGamer@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EPICGAMER@GMAIL.COM",
                            NormalizedUserName = "EPICGAMER",
                            PasswordHash = "AQAAAAIAAYagAAAAEAV1PxglbXbqpSQIgKR8AT3tJgQlgnFiKzMrxMCcIvQRO37qaciy8Iy1RzHhC3I1CQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "519911e3-753b-4015-b079-eab8e5698de4",
                            TwoFactorEnabled = false,
                            UserName = "EpicGamer"
                        },
                        new
                        {
                            Id = "77777777-7777-7777-7777-777777777777",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe5d6c09-3964-41f5-b1db-19bdabdee179",
                            Email = "TheLegend27@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "THELEGEND27@GMAIL.COM",
                            NormalizedUserName = "THELEGEND27",
                            PasswordHash = "AQAAAAIAAYagAAAAEB+hCw9FPrxxlMA+6gAZEsz8XB16HKC/SDGeM+mITnoLah041O175vZQ/jPlG2UlLQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "49263ca7-3bc4-4c4f-bf04-8d95b4d46b97",
                            TwoFactorEnabled = false,
                            UserName = "TheLegend27"
                        },
                        new
                        {
                            Id = "88888888-8888-8888-8888-888888888888",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5803b757-0c49-4861-9e9c-fd9a89767fa4",
                            Email = "GameAddict@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMEADDICT@GMAIL.COM",
                            NormalizedUserName = "GAMEADDICT",
                            PasswordHash = "AQAAAAIAAYagAAAAEP6RS7H49Bf4DvPmk+xdJA7QBTqJ0u58q3BjLvFWNFxeihhlpAwTLPmYMFlRmLAy+w==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "240d48c4-b9aa-471b-b747-e5689a458799",
                            TwoFactorEnabled = false,
                            UserName = "GameAddict"
                        },
                        new
                        {
                            Id = "99999999-9999-9999-9999-999999999999",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4218c47c-2764-4e2a-ae8b-f4912b1aa2f0",
                            Email = "XxGamerxX@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "XXGAMERXX@GMAIL.COM",
                            NormalizedUserName = "XXGAMERXX",
                            PasswordHash = "AQAAAAIAAYagAAAAEGV2xChHatc9rptc2cRqtHYM4IQ9hTm0fRTI26uZ6fk0bAm5+yw37qiRxZ33NMW1Bg==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "84ca7909-90aa-4dc3-a970-0ac612cf165f",
                            TwoFactorEnabled = false,
                            UserName = "XxGamerxX"
                        },
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d2d436f-fb7f-414c-8035-06197bf7c331",
                            Email = "SwordMaster@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SWORDMASTER@GMAIL.COM",
                            NormalizedUserName = "SWORDMASTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPfAv7RkKwtP5pPkta99BDIgw6msRykUIgxoJYxgD7b/e4HxwGIQES/h9PF2CS6Pdw==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "f3b1327c-773d-42ff-ace3-c24809c5e897",
                            TwoFactorEnabled = false,
                            UserName = "SwordMaster"
                        },
                        new
                        {
                            Id = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4415c0d-3d90-448b-b213-781c87ae43c3",
                            Email = "PixelWarrior@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIXELWARRIOR@GMAIL.COM",
                            NormalizedUserName = "PIXELWARRIOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEMzbANiOUAjStBqKDcbQunRmTYscEQqdtki5a30wenksy60GAKljdkOg/8BLi8Cthg==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "277d3602-ab02-423b-b1cd-1d1d27a34824",
                            TwoFactorEnabled = false,
                            UserName = "PixelWarrior"
                        },
                        new
                        {
                            Id = "cccccccc-cccc-cccc-cccc-cccccccccccc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "41bd7167-71e0-43e5-baa6-d3238acdfad9",
                            Email = "GamingGeek@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMINGGEEK@GMAIL.COM",
                            NormalizedUserName = "GAMINGGEEK",
                            PasswordHash = "AQAAAAIAAYagAAAAEBVrfPJQQCmpS0RiDNXLn3RRftMQqOQRTAzX5MFWLPK0k8rd8mTLkCjpYIEjm+sn0A==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "bf082f84-9b99-4b55-8840-e7889a663a2a",
                            TwoFactorEnabled = false,
                            UserName = "GamingGeek"
                        },
                        new
                        {
                            Id = "dddddddd-dddd-dddd-dddd-dddddddddddd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "60e5ddfb-4a07-49b7-8fbe-e10d843dbf5d",
                            Email = "GameOn123@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMEON123@GMAIL.COM",
                            NormalizedUserName = "GAMEON123",
                            PasswordHash = "AQAAAAIAAYagAAAAEGZ/uuIzwYypB7JWS4MWtF59omK+11JLdQc/2dT2FaCcXg2188t/hq79UId2vM7SDg==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "37228f58-9340-4b23-9406-c80ecffda16a",
                            TwoFactorEnabled = false,
                            UserName = "GameOn123"
                        },
                        new
                        {
                            Id = "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38935d2d-3793-44a4-9423-256851b8f1c5",
                            Email = "FragMeister@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "FRAGMEISTER@GMAIL.COM",
                            NormalizedUserName = "FRAGMEISTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEK6r23mk+AWlWnwZejGOAYzmHM4+6DGAjR/22W6YxdUcTBkVXP63YG+2oLQYmHG4XQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "caf07899-102a-49e0-aaeb-2aae7cd970b1",
                            TwoFactorEnabled = false,
                            UserName = "FragMeister"
                        },
                        new
                        {
                            Id = "ffffffff-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14283a71-beed-410c-9069-042183e17a22",
                            Email = "DigitalWarrior@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DIGITALWARRIOR@GMAIL.COM",
                            NormalizedUserName = "DIGITALWARRIOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ+70OHj9Jk/r7EeFYVREDcRaDfd+6Xfy0lw9FYEV4UmiOaymbGga+IjkejrqwlgIQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "bd64ecdf-6190-435c-b4cc-8d81f6a2f0a2",
                            TwoFactorEnabled = false,
                            UserName = "DigitalWarrior"
                        },
                        new
                        {
                            Id = "00000002-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "642d8628-33b9-43d1-9560-47eec97094f0",
                            Email = "ControllerKing@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTROLLERKING@GMAIL.COM",
                            NormalizedUserName = "CONTROLLERKING",
                            PasswordHash = "AQAAAAIAAYagAAAAELk4Z3/RJ4LQgQ/tGhBv0a4n9WO3qSIcqbh1Vw1VVDvD/JQToPg56VGP7VbtNLmpCw==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "878cb454-63cc-48ce-9747-b0d5f1688db0",
                            TwoFactorEnabled = false,
                            UserName = "ControllerKing"
                        },
                        new
                        {
                            Id = "11112222-3333-4444-5555-666677778888",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "822fc2a3-4fae-432e-bd6c-70a58f1c059f",
                            Email = "LevelUp@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LEVELUP@GMAIL.COM",
                            NormalizedUserName = "LEVELUP",
                            PasswordHash = "AQAAAAIAAYagAAAAEB4iyRV2TzbK3XcXH7m3AmWCYYh1HeNKTybUMNqY8xFfJ962tjefUBlJE2pXxmtO/g==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "4d1a3c3b-485a-4649-9468-1449e16a1ff7",
                            TwoFactorEnabled = false,
                            UserName = "LevelUp"
                        },
                        new
                        {
                            Id = "11111111-1111-1211-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9689e38b-0354-4a3d-aff3-aa2af431533d",
                            Email = "PwnedYou@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PWNEDYOU@GMAIL.COM",
                            NormalizedUserName = "PWNEDYOU",
                            PasswordHash = "AQAAAAIAAYagAAAAEAp2x4Mtwj4HCv477UdThFJZ4SPQMVOprb1wSYZd3A9K51TF1jDBE1fn4FWOyEFsug==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "cbf33cb1-7911-4751-8e0c-1a30eb3a1d4f",
                            TwoFactorEnabled = false,
                            UserName = "PwnedYou"
                        },
                        new
                        {
                            Id = "21111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cfa0594d-48b7-46fd-94b6-06a97c763e5f",
                            Email = "QuestHunter@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "QUESTHUNTER@GMAIL.COM",
                            NormalizedUserName = "QUESTHUNTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEO3giZ5DFHKkmsiZyPQ2XC75W3pVASf9nqmH21X4gYmLTEqmIj6xKziH3H1LPpcgmA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "572e0ff6-7b47-41d0-b13d-c8e56f2a8b87",
                            TwoFactorEnabled = false,
                            UserName = "QuestHunter"
                        },
                        new
                        {
                            Id = "31111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "35aa492e-933d-4697-afc2-7a5a7cbfc39c",
                            Email = "RetroGamer@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RETROGAMER@GMAIL.COM",
                            NormalizedUserName = "RETROGAMER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPAsSmMWBMGZVJ0I5XlmtgWmAAskTJ6NMjlMSXy5lD6CwiYKVyb68xqjqXoTqfSdQQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "01132823-fbf6-4671-a720-33cc710243b6",
                            TwoFactorEnabled = false,
                            UserName = "RetroGamer"
                        },
                        new
                        {
                            Id = "41111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1195541-d637-4183-b543-27090533edd7",
                            Email = "ArcadeHero@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARCADEHERO@GMAIL.COM",
                            NormalizedUserName = "ARCADEHERO",
                            PasswordHash = "AQAAAAIAAYagAAAAEOiTIWfnwOh8VSVK3zyeTaRoeOQX1w9VdWFhWHbdV+LI+Hlf8G+657Bq4rLjj1bJEw==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "f59b070e-0cc4-46cd-9763-abd16e64dbac",
                            TwoFactorEnabled = false,
                            UserName = "ArcadeHero"
                        },
                        new
                        {
                            Id = "51111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f399a9d-0649-418f-aadc-9020fb6f3493",
                            Email = "ConsoleChamp@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONSOLECHAMP@GMAIL.COM",
                            NormalizedUserName = "CONSOLECHAMP",
                            PasswordHash = "AQAAAAIAAYagAAAAECXb9vtiinlsYjGtqgdUwc8Z6WZ683ar7LUGyqEpTUgvGDORBBngU0OIkuz2yjyKuQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "58ced55b-7266-414a-a614-e779ff1b76c4",
                            TwoFactorEnabled = false,
                            UserName = "ConsoleChamp"
                        },
                        new
                        {
                            Id = "61111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "589387b3-85fe-4116-a95f-df8ac55f68f0",
                            Email = "OnlineWarrior@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ONLINEWARRIOR@GMAIL.COM",
                            NormalizedUserName = "ONLINEWARRIOR",
                            PasswordHash = "AQAAAAIAAYagAAAAECTUY6FPtFJKkByugnJojnWLVO2w3z4V3EJjnitQKxq0vgNDBlzughmGzYVthIky4w==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "6cd91411-b82a-4e26-aff1-00e2436c845f",
                            TwoFactorEnabled = false,
                            UserName = "OnlineWarrior"
                        },
                        new
                        {
                            Id = "71111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f156def-f282-400f-b90d-6cb25a4b6528",
                            Email = "GamerGirl@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMERGIRL@GMAIL.COM",
                            NormalizedUserName = "GAMERGIRL",
                            PasswordHash = "AQAAAAIAAYagAAAAEBglBB5fcX54d4ErbHekY1/8ZqDvLhyNAbYIY+GWfKGFdXQKvc2LXf/YkuHhyZJA2w==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "910c46e5-ee64-455f-9daa-41ad67c0d60a",
                            TwoFactorEnabled = false,
                            UserName = "GamerGirl"
                        },
                        new
                        {
                            Id = "81111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "370c2e55-9e9e-4790-90bf-c9fe6ea8148c",
                            Email = "GameNerd@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMENERD@GMAIL.COM",
                            NormalizedUserName = "GAMENERD",
                            PasswordHash = "AQAAAAIAAYagAAAAEP/NkVv878NnyXxX18spE7wggs3sbl/TFvBhsWz77E2mZqDrctrSU7w8LHln/3KpTQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "5c19aaca-3203-4e0f-a6e5-66ca46131c28",
                            TwoFactorEnabled = false,
                            UserName = "GameNerd"
                        },
                        new
                        {
                            Id = "91111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fdbe180f-8f4f-424c-b53f-4c901092e3a9",
                            Email = "ZombieSlayer@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZOMBIESLAYER@GMAIL.COM",
                            NormalizedUserName = "ZOMBIESLAYER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMX/EXRG+GZcaxP6HBvRka9J4AkQC1EENHUM/gI5wpQVkmZ9K3KxxCm4Fh3S8LYing==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "edc40cf9-c410-4f66-9e20-dc7bf89d1138",
                            TwoFactorEnabled = false,
                            UserName = "ZombieSlayer"
                        },
                        new
                        {
                            Id = "12111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0cb8fae3-6d3f-4902-b88b-b0f2f4ca73da",
                            Email = "MageMaster@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAGEMASTER@GMAIL.COM",
                            NormalizedUserName = "MAGEMASTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEBebvExKaEPE5rNbaxe7cqH2yc/J1nSg7trXId96CJLqRkeu+5exvRWmxzqGYSuPZA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "e51d94f0-df99-471e-a1cf-e340b799da50",
                            TwoFactorEnabled = false,
                            UserName = "MageMaster"
                        },
                        new
                        {
                            Id = "13111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7995ee2-19d1-4457-a1a5-890b4e34484a",
                            Email = "LootHunter@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LOOTHUNTER@GMAIL.COM",
                            NormalizedUserName = "LOOTHUNTER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPogQDIqsKuytPU0Gd3+Wc+3rSZwOmQTXkn7ZvY9iOqQ7Jlyb1G/eKB5M5GgPdAORQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "16a9657b-2bc0-4909-b1cd-ed7f9c6247fb",
                            TwoFactorEnabled = false,
                            UserName = "LootHunter"
                        },
                        new
                        {
                            Id = "14111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04cae4d0-94c6-430b-8b01-5a731c5a60ed",
                            Email = "DungeonCrawler@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DUNGEONCRAWLER@GMAIL.COM",
                            NormalizedUserName = "DUNGEONCRAWLER",
                            PasswordHash = "AQAAAAIAAYagAAAAECVvHUpZKjhrxMbAlkVaROj/VXklpQJ1xByLYUuZ+avCY5HaETJyN9evNuBr7Idqpw==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "9397f095-dd93-4616-a006-f8872f786a76",
                            TwoFactorEnabled = false,
                            UserName = "DungeonCrawler"
                        },
                        new
                        {
                            Id = "15111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d97e35ff-299e-4821-b27d-8c300cf62390",
                            Email = "HighScore@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HIGHSCORE@GMAIL.COM",
                            NormalizedUserName = "HIGHSCORE",
                            PasswordHash = "AQAAAAIAAYagAAAAEPjl9tqWsMO8xhOei2kVT1jYf5kXutGD9b+RyRET3AGafyhA+J9w1Q/iYxweTuwFpQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "a608a532-db3a-4245-82b2-d02d96eb26d5",
                            TwoFactorEnabled = false,
                            UserName = "HighScore"
                        },
                        new
                        {
                            Id = "16111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2a178081-77d3-4cb9-80b3-01d70777aadc",
                            Email = "BossBattler@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOSSBATTLER@GMAIL.COM",
                            NormalizedUserName = "BOSSBATTLER",
                            PasswordHash = "AQAAAAIAAYagAAAAENgKr/cP+TKDKBndziQnwI01mNHVxoGmPso8aRFK5ZuKjZPBPgy802oA2F1TAtP8fQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "444b459f-3ed8-4239-b512-5d46eb347bd1",
                            TwoFactorEnabled = false,
                            UserName = "BossBattler"
                        },
                        new
                        {
                            Id = "17111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9b5f77b-9f10-4359-954b-30d446a7d939",
                            Email = "SniperElite@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SNIPERELITE@GMAIL.COM",
                            NormalizedUserName = "SNIPERELITE",
                            PasswordHash = "AQAAAAIAAYagAAAAEOK14fhndZvu0vW4pzB3lcIjM0i+gStkIV7LlxdCrH01ZcgDxeqoegHpzBqqqpa8Hw==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "cb426534-aeea-44c7-9c9e-4b8e9d7c6398",
                            TwoFactorEnabled = false,
                            UserName = "SniperElite"
                        },
                        new
                        {
                            Id = "18111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d034df47-4d00-428e-b904-74fb0325f979",
                            Email = "GameGuru@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMEGURU@GMAIL.COM",
                            NormalizedUserName = "GAMEGURU",
                            PasswordHash = "AQAAAAIAAYagAAAAEOcsPoEBkjzh3u6uFCs+EvVPOz9sWkNYE84hl72FTK5/7QY0T1hLPug0TBUGsjHQgQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "0577cb09-840a-4751-99a7-07f99acf488a",
                            TwoFactorEnabled = false,
                            UserName = "GameGuru"
                        },
                        new
                        {
                            Id = "19111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6806373d-b6ba-4d61-b24b-605555a2e641",
                            Email = "SpeedRunner@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SPEEDRUNNER@GMAIL.COM",
                            NormalizedUserName = "SPEEDRUNNER",
                            PasswordHash = "AQAAAAIAAYagAAAAEO3FfjbgA5+dr9e3tq8GOCwrk8oYWmNlylAS1thKgfUmjNM6wsvu2zL9cmPeJ9eqxA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c6b67be9-baa4-453d-ae89-8d0a799c1fb5",
                            TwoFactorEnabled = false,
                            UserName = "SpeedRunner"
                        },
                        new
                        {
                            Id = "11211111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f0724d1-7123-477a-b9cf-1c820ded4f94",
                            Email = "eSportsChamp@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ESPORTSCHAMP@GMAIL.COM",
                            NormalizedUserName = "ESPORTSCHAMP",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4Et0luM3D7ZHOm/a0UUyPOEHUI8pRNbYnaGshEoMqAY7IIdC0NyKPKuX60PCFWog==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "7e4098e7-81aa-4bf7-9758-b32de715599c",
                            TwoFactorEnabled = false,
                            UserName = "eSportsChamp"
                        },
                        new
                        {
                            Id = "11311111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01b4d14b-b2a6-45c5-894c-c39d9111d0d2",
                            Email = "GameWizard@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMEWIZARD@GMAIL.COM",
                            NormalizedUserName = "GAMEWIZARD",
                            PasswordHash = "AQAAAAIAAYagAAAAEBXVNwo2RWuEkCRjozajWK6z6pzqzLVpuBG7NIxNUy2YzgRIBHZFBgmknn4tviIPPQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c723b194-6743-43ae-a3f2-160a686f3d0b",
                            TwoFactorEnabled = false,
                            UserName = "GameWizard"
                        },
                        new
                        {
                            Id = "11411111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b92302f8-9a32-48ef-b065-692d4dd6d289",
                            Email = "GamingJunkie@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMINGJUNKIE@GMAIL.COM",
                            NormalizedUserName = "GAMINGJUNKIE",
                            PasswordHash = "AQAAAAIAAYagAAAAEHOb/ACHe80oHOC8ce1R6roJAIbzX7q6G5jIf2XbK3eu79560hUSJ3tv0h49kuT3yA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "a604ebe7-9e88-4773-a7f3-53e2f46e5480",
                            TwoFactorEnabled = false,
                            UserName = "GamingJunkie"
                        },
                        new
                        {
                            Id = "11511111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ddc35ce-de95-4f6e-bd27-3f59f6d45c0e",
                            Email = "PixelPirate@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PIXELPIRATE@GMAIL.COM",
                            NormalizedUserName = "PIXELPIRATE",
                            PasswordHash = "AQAAAAIAAYagAAAAEBxq6cQC4bYU+GTF8uZUQPGC5E3sfIKjPkbrLI5XVLBQOVkhGKmg5fP7eJguc+tYGA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "9a94511a-89d4-4784-955f-b7dc6a627a8f",
                            TwoFactorEnabled = false,
                            UserName = "PixelPirate"
                        },
                        new
                        {
                            Id = "11611111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f6ed6b0-3147-4086-a3c2-8b263d0e6c08",
                            Email = "RPGHero@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RPGHERO@GMAIL.COM",
                            NormalizedUserName = "RPGHERO",
                            PasswordHash = "AQAAAAIAAYagAAAAEPEwmEdsewfeUBImOnh9ArmauhUmPtiQwvzFD9IynxDY795w66d0bJhjAMxjtTe4ew==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c0ecf633-ca24-401e-ba5d-03b8d876fa33",
                            TwoFactorEnabled = false,
                            UserName = "RPGHero"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "77ec7b31-d322-4f02-93df-4b52dd5c6632",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "37cadf13-b04f-4467-94a3-34ede27d31cd",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "22222222-2222-2222-2222-222222222222",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "33333333-3333-3333-3333-333333333333",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "44444444-4444-4444-4444-444444444444",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "55555555-5555-5555-5555-555555555555",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "66666666-6666-6666-6666-666666666666",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "77777777-7777-7777-7777-777777777777",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "88888888-8888-8888-8888-888888888888",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "99999999-9999-9999-9999-999999999999",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "cccccccc-cccc-cccc-cccc-cccccccccccc",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "dddddddd-dddd-dddd-dddd-dddddddddddd",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "ffffffff-ffff-ffff-ffff-ffffffffffff",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "00000002-0000-0000-0000-000000000000",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "11112222-3333-4444-5555-666677778888",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "11111111-1111-1211-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "21111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "31111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "41111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "51111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "61111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "71111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "81111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "91111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "12111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "13111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "14111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "15111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "16111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "17111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "18111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "19111111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "11211111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "11311111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "11411111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "11511111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        },
                        new
                        {
                            UserId = "11611111-1111-1111-1111-111111111111",
                            RoleId = "37cadf13-b04f-4467-94a3-34ede27d31cd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HypeHubDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HypeHubDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HypeHubDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HypeHubDAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
