name: Logic-Tests
on:
  push:
    branches:
      - main
    paths:
      - 'HypeHub/HypeHubLogic/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./HypeHub/HypeHub.sln

      - name: Build
        run: dotnet build ./HypeHub/HypeHub.sln --no-restore
   
      - name: Test
        env:
          AzureKeyVault:VaultUri: ${{ secrets.AZUREKEYVALUT_VAULTURI }}
          IssuerSigningKey: ${{ secrets.ISSUER_SIGNING_KEY }}
          JWT:VALIDAUDIENCE: ${{ secrets.JWT_VALIDAUDIENCE }}
          JWT:VALIDISSUER: ${{ secrets.JWT_VALIDISSUER }}
          JWT:TOKENVALIDITYINMINUTES: ${{ secrets.JWT_TOKENVALIDITYINMINUTES}}
        run: dotnet test ./HypeHub/HypeHubTests/HypeHubTests.csproj --filter FullyQualifiedName~ServicesTests --no-build --verbosity normal
